tap "brewforge/extras"
tap "nikitabobko/tap"
tap "quintrino/godspeed-cli"
tap "unsecretised/tap"
# Spell checker with better logic than ispell
brew "aspell"
# Mozilla CA certificate store
brew "ca-certificates"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Get/set bluetooth power and discoverable state
brew "blueutil"
# Yet another cross-platform graphical process/system monitor
brew "bottom"
# Cross-platform make
brew "cmake"
# TIFF library and utilities
brew "libtiff"
# Dotfile manager and templater written in rust
brew "dotter"
# View disk space usage and delete unwanted data, fast
brew "dua-cli"
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Command-line tool to interact with exercism.io
brew "exercism"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Plugin manager for the Fish shell
brew "fisher"
# Command-line tools for fly.io services
brew "flyctl"
# Command-line fuzzy finder written in Go
brew "fzf"
# Google Drive CLI Client
brew "gdrive"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Alias for git commit --fixup <ref>
brew "git-fixup"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Post-modern modal text editor
brew "helix"
# Add GitHub support to git on the command-line
brew "hub"
# YAML Parser
brew "libyaml"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Create, run, and share large language models (LLMs)
brew "ollama"
# General-purpose speech recognition model
brew "openai-whisper"
# File management automation tool
brew "organize-tool"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Modern replacement for ps written in Rust
brew "procs"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Cross-shell prompt for astronauts
brew "starship"
# Open source continuous file synchronization application
brew "syncthing"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Execute commands when watched files change
brew "watchexec"
# Check your $HOME for unwanted files and directories
brew "xdg-ninja"
# Friendly and fast tool for sending HTTP requests
brew "xh"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# Flexible and fast Zsh plugin manager
brew "zinit"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Additional completion definitions for zsh
brew "zsh-completions"
# Rust-based Godspeed CLI
brew "quintrino/godspeed-cli/godspeed-cli", trusted: true
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Time tracker
cask "activitywatch"
# AeroSpace is an i3-like tiling window manager for macOS
cask "nikitabobko/tap/aerospace", trusted: true
# Application launcher and productivity software
cask "alfred"
# Enable Windows-like alt-tab
cask "alt-tab"
# Memory training application
cask "anki"
# Universal chat app powered by Matrix
cask "beeper"
# Desktop password and login vault
cask "bitwarden"
# Web browser focusing on privacy
cask "brave-browser@beta"
# Email client
cask "emclient"
# Cross-platform Text Expander written in Rust
cask "espanso"
# Web browser
cask "firefox"
cask "font-jetbrains-mono-nerd-font"
# Keyboard-focused todo manager
cask "godspeed"
# Keyboard shortcuts for every button on your screen
cask "homerow"
# Visual exploration of genomic data
cask "igv-desktop"
# Free and open-source media player
cask "iina"
# System monitoring app
cask "istat-menus"
# Keyboard customiser
cask "karabiner-elements"
# Open-source cross-platform alternative to AirDrop
cask "localsend"
# Dual-pane file manager
cask "nimble-commander"
# Open-source software for live streaming and screen recording
cask "obs"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Client for Proton Drive
cask "proton-drive"
# Bridges Proton Mail to email clients supporting IMAP and SMTP protocols
cask "proton-mail-bridge"
# Instant messaging application focusing on security
cask "signal@beta"
# Team communication and collaboration software
cask "slack"
# Remote access and connectivity software focused on security
cask "teamviewer"
# Customizable timing of breaks
cask "time-out"
# Transcribe on your own
cask "brewforge/extras/vibe", trusted: true
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Gecko based web browser
cask "zen"
# Video communication and virtual meeting platform
cask "zoom"
