#!/bin/sh

export TERM="xterm-256color"
export CLICOLOR=1
export EDITOR=code
export GIT_EDITOR='code --goto --new-window --wait'
export EXA_GRID_ROWS=8
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export HEX_HOME="$XDG_CONFIG_HOME/hex"
export BUNDLE_USER_HOME="$XDG_CONFIG_HOME/bundle"
export ASDF_DATA_DIR="$XDG_CONFIG_HOME/asdf"
export ASDF_DEFAULT_TOOL_VERSIONS_FILENAME="$XDG_CONFIG_HOME/asdf/.tool-versions"
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export HTTPIE_CONFIG_DIR="$XDG_CONFIG_HOME/httpie"
export GEMRC="$XDG_CONFIG_HOME/ruby/gemrc"
export _Z_DATA="$XDG_DATA_HOME/z/z"
export FRESH_RCFILE="$HOME/.dotfiles/config/fresh/freshrc"
export LOLCOMMITS_DIR="$XDG_DATA_HOME/lolcommits"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"
export IRBRC="$XDG_CONFIG_HOME/ruby/irbrc"
export ELM_HOME="$XDG_CONFIG_HOME/elm"
export FRESH_PATH="$XDG_CONFIG_HOME/fresh"

if [ -f "$XDG_CONFIG_HOME/asdf/.tool-versions" ]; then
  ASDF_GLOBAL_RUBY=$(grep ruby "$XDG_CONFIG_HOME/asdf/.tool-versions")
  export ASDF_GLOBAL_RUBY
else
  echo "File $XDG_CONFIG_HOME/asdf/.tool-versions does not exist."
fi
