#!/bin/zsh

#iTerm

#the edit command has been created by creating a symlink in the deploy script to editor of choice.

alias e='edit'
alias ea='edit -a .'

alias zhist='edit $HOME/.history/zsh/'

alias ali='edit $HOME/.dotfiles/aliases'
alias b='bat'
alias dot='cd $HOME/.dotfiles'
alias zrc='cd $HOME/.dotfiles && edit zshrc'
alias freq='history 0 | sed -E "s/ *[0-9]+\*? *[0-9 :-]+ *//" | sort | uniq -c | sort -rn | head -50'
alias setup='edit $HOME/Google\ Drive/Sync/Mac/setup'
alias lsa='ls -a'
alias profile='edit $HOME/Google\ Drive/Sync/Mac/iTerm/.profile'
alias pass='eval "$(ssh-agent -s)"; ssh-add $HOME/.ssh/id_rsa; export PATH="/usr/local/opt/openssl/bin:$PATH"'
alias hn='hnote'
alias now='date +"%T"'
alias ls='echo "You should use bat either exa or l instead"'
alias l='exa --long --grid --all --header --git --classify'
alias up='cd ..'
alias md='mkdir -p'

#Git

alias guns='git reset'
alias gunc='git reset HEAD^'
alias axe='git log --patch -S'
alias gitback='git show $(git log --format=%h^ master..HEAD | tail -n 1) --format=%cr'
alias glob='glo master..HEAD'
alias gfc='git fixup --commit'
alias grc='git_open_conflicts && git add . && git rebase --continue'
alias git_track_untracked='git ls-files --others --exclude-standard | xargs git add -N'
alias amend='g commit --amend --no-edit'
alias grasm='git rebase --autosquash --autostash master'
alias gb='git log --oneline master..HEAD'
alias gs='git status --long'
alias gd='git diff --ignore-all-space --ignore-blank-lines'
alias gds='git diff --ignore-all-space --ignore-blank-lines --staged'
alias upstream='git pull upstream master'
alias push='git push origin HEAD'
alias commit='git commit -v '
alias doccommit='OVERCOMMIT_DISABLE=1 commit'
alias ocd='OVERCOMMIT_DISABLE=1 '
alias gp='git pull'
alias co='git checkout'
alias gcm='git checkout master'
alias gdm='git diff master..HEAD'
alias prod='git push production master'
alias dep='push && prod'
alias gc='git config -l'
alias show='git show --ignore-all-space --ignore-blank-lines'
alias gcp='git checkout -p'
alias gcmp='gcm && gp'
alias gundo='git reset HEAD~1 '
alias add='git_track_untracked && git add -p && git_untrack_new_blank && git status --short && logic'
alias logic='echo -e "\033[1;31m If applied this commit will... \033[0m"'
alias force-push='git push origin HEAD --force-with-lease'
alias afp='amend && force-push'
alias gitroot='cd $(git rev-parse --show-toplevel)'
# open repo in browser
alias gh='open $(git config remote.origin.url | sed "s/git@\(.*\):\(.*\).git/https:\/\/\1\/\2/")/tree/$(git symbolic-ref --quiet --short HEAD )'
# Open current branch
alias ghb='gh tree/$(git symbolic-ref --quiet --short HEAD )'
# Open current directory/file in current branch
alias ghbf='gh tree/$(git symbolic-ref --quiet --short HEAD )/$(git rev-parse --show-prefix)'
# Open current directory/file in master branch
alias ghf='gh tree/master/$(git rev-parse --show-prefix)'

#Ruby

alias ru='bundle exec rubocop'
alias rus='ru spec/* --display-only-fail-level-offenses --fail-level=C'
alias rua='ru --auto-correct --only '
alias geml='cp $HOME/.dotfiles/ruby/Gems.local Gemfile.local'

#Rails

alias rc='bundle exec rails console'
alias roff='kill -9 $(lsof -i tcp:3000 -t)'
alias pryrc='pry -r ./config/environment'
alias ras='bundle exec rails server'
alias work='bin/rake jobs:work'
alias rt='bundle exec rake test'
alias rr='bundle exec rspec --format documentation'
alias be='bundle exec'
alias bi='bundle install'

#Docker

alias dcu='docker-compose up'
alias sup='vsplit_tab dcu && fs'

#Directory Jumping

alias d='dirs -v | head -10'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

# CultureAmp

alias ca='cd $HOME/Code/CultureAmp'
alias jep='cd $HOME/Code/CultureAmp/JuniorEngineer'
alias ys='BROWSER=none yarn start'
alias mu='cd $HOME/Code/CultureAmp/murmur'
alias mut='bin/murmur-tmux start'
alias mus='bin/murmur-tmux stop'

#Folders

alias drive='cd $HOME/Google\ Drive/'


#Fun

alias star='telnet towel.blinkenlights.nl'

# to unalias something just do 'unalias foo'

#alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm install npm -g; npm update -g; sudo gem update --system; sudo gem update; sudo gem cleanup'
