#!/bin/zsh

export TERM="xterm-256color"
export CLICOLOR=1
export EDITOR=code
export EXA_GRID_ROWS=8
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ASDF_DATA_DIR="$XDG_CONFIG_HOME/asdf"
export ASDF_DEFAULT_TOOL_VERSIONS_FILENAME="$XDG_CONFIG_HOME/asdf/tool-versions"
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export HTTPIE_CONFIG_DIR="$XDG_CONFIG_HOME/httpie"
export GEMRC="$XDG_CONFIG_HOME/ruby/gemrc"
export _Z_DATA="$XDG_DATA_HOME/z/z"
export FRESH_RCFILE="$HOME/.dotfiles/freshrc"
export LOLCOMMITS_DIR="$XDG_DATA_HOME/lolcommits"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"
export IRBRC="$XDG_CONFIG_HOME/ruby/irbrc"
export ELM_HOME="$XDG_CONFIG_HOME/elm"
export FRESH_PATH="$XDG_CONFIG_HOME/fresh"

declare -A ZPLGM
ZPLGM[HOME_DIR]="$XDG_CONFIG_HOME/zplugin"
ZPLGM[BIN_DIR]="$XDG_CONFIG_HOME/zplugin/bin"

if [ -f $XDG_CONFIG_HOME/asdf/.tool-versions ]; then
  export ASDF_GLOBAL_RUBY=`cat $XDG_CONFIG_HOME/asdf/.tool-versions | grep ruby`
else
  echo "File $XDG_CONFIG_HOME/asdf/.tool-versions does not exist."
fi
