#!/bin/zsh
# freshshell.com
#
# Examples:
#
#   fresh twe4ked/dotfiles shell/functions/\*
#   fresh jasoncodes/dotfiles shell/aliases/rails.sh
#   fresh jasoncodes/dotfiles config/tmux.conf --file
#
# See http://freshshell.com/readme for documentation.

fresh freshshell/fresh bin/fresh --bin
fresh freshshell/fresh contrib/source-build.sh --file=~/.zshrc

fresh zshrc
fresh aliases
fresh functions
fresh fzf.zsh

# Git
fresh-options --file
  fresh git/\*
fresh-options

# fresh profile
# fresh pryrc --file=~/.pryrc
