#!/bin/zsh
# freshshell.com
#
# Examples:
#
#   fresh twe4ked/dotfiles shell/functions/\*
#   fresh jasoncodes/dotfiles shell/aliases/rails.sh
#   fresh jasoncodes/dotfiles config/tmux.conf --file
#
# See http://freshshell.com/readme for documentation.

fresh freshshell/fresh bin/fresh --bin
fresh freshshell/fresh contrib/source-build.sh --file=~/.zshrc

fresh environment
fresh zshrc
fresh powerlevel9k
fresh zplugin
fresh completions
fresh aliases
fresh functions
fresh fzf.zsh
fresh lessrc
fresh https://gitlab.com/ellsclytn/dotfiles.git bin/extract --bin --ref=5165c8d0

# Git
fresh git/ignore --file=$XDG_CONFIG_HOME/git/ignore
fresh git/config --file=$XDG_CONFIG_HOME/git/config --filter=erb

fresh-options --file=$XDG_CONFIG_HOME/Karabiner/karabiner.json
  fresh config/Karabiner/karabiner.json
fresh-options

# fresh profile
fresh pryrc --file=$XDG_CONFIG_HOME/pry/pryrc
fresh gemrc --file=$XDG_CONFIG_HOME/gem/gemrc
fresh railsrc --file=~/.railsrc
fresh hushlogin --file=~/.hushlogin
fresh tool-versions --file=$XDG_CONFIG_HOME/asdf/.tool-versions
