#!/bin/zsh
# freshshell.com
#
# Examples:
#
#   fresh twe4ked/dotfiles shell/functions/\*
#   fresh jasoncodes/dotfiles shell/aliases/rails.sh
#   fresh jasoncodes/dotfiles config/tmux.conf --file
#
# See http://freshshell.com/readme for documentation.

fresh freshshell/fresh bin/fresh --bin
fresh zshrc --file=~/.zshrc

fresh path
fresh environment
fresh zsh
fresh powerlevel9k
fresh zplugin
fresh completions
fresh aliases
fresh functions
fresh fzf.zsh
fresh lessrc
fresh https://gitlab.com/ellsclytn/dotfiles.git bin/extract --bin --ref=5165c8d0

# Git
fresh git/cc_menu --bin
fresh git/ignore --file=$XDG_CONFIG_HOME/git/ignore
fresh git/config --file=$XDG_CONFIG_HOME/git/config --filter=erb

# fresh profile
fresh ruby/pryrc --file=$XDG_CONFIG_HOME/pry/pryrc
fresh ruby/irbrc --file=$XDG_CONFIG_HOME/ruby/irbrc
fresh ruby/gemrc --file=$XDG_CONFIG_HOME/ruby/gemrc
fresh ruby/default-gems --file=$XDG_CONFIG_HOME/asdf/default-gems
fresh ruby/railsrc --file=~/.railsrc
fresh hushlogin --file=~/.hushlogin
fresh tool-versions --file=$XDG_CONFIG_HOME/asdf/.tool-versions
fresh asdfrc --file=$XDG_CONFIG_HOME/asdf/asdfrc


fresh_after_build(){
  ln -sf ~/.dotfiles/apps/vs-code/settings ~/Library/Application\ Support/Code/User/settings.json
  ln -sf ~/.dotfiles/apps/vs-code/keys ~/Library/Application\ Support/Code/User/keybindings.json
  ln -sf ~/.dotfiles/config/karabiner/karabiner.json $XDG_CONFIG_HOME/karabiner/karabiner.json
}
