#!/bin/zsh
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "djui/alias-tips"
export ZSH_PLUGINS_ALIAS_TIPS_REVEAL=1

zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme

zplug "lukechilds/zsh-nvm"
export NVM_LAZY_LOAD=true

zplug 'wfxr/forgit', defer:1
forgit_diff=gid

zplug "zdharma/fast-syntax-highlighting", from:github

zplug "zsh-users/zsh-autosuggestions"
bindkey '^[[[CE' autosuggest-execute


if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
fpath=(/usr/local/share/zsh-completions $fpath)
autoload -U compinit
compinit

#AutoSuggest config
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=cyan'

compdef g=git
