#!/bin/zsh
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "djui/alias-tips"
zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
zplug "lukechilds/zsh-nvm"
zplug "plugins/history", from:oh-my-zsh
zplug 'wfxr/forgit', defer:1
zplug "zdharma/fast-syntax-highlighting", from:github
zplug "zsh-users/zsh-autosuggestions"
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
fpath=(/usr/local/share/zsh-completions $fpath)
autoload -U compinit
compinit

#AutoSuggest config
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=cyan'
bindkey '^[[[CE' autosuggest-execute

compdef g=git
