#!/bin/zsh
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "djui/alias-tips"
export ZSH_PLUGINS_ALIAS_TIPS_REVEAL=1

zplug "rupa/z", use:z.sh

zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme

zplug 'wfxr/forgit', defer:1
forgit_diff=gid
forgit_restore=forgit_restore

zplug "zdharma/fast-syntax-highlighting", from:github

zplug "andrewferrier/fzf-z", from:github

zplug "zsh-users/zsh-autosuggestions"
bindkey '^[[[CE' autosuggest-execute


if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
fpath=(/usr/local/share/zsh-completions $fpath)
autoload -U compinit
compinit

#AutoSuggest config
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=cyan'

compdef g=git
compdef gcf=git-fixup

source /usr/local/opt/asdf/asdf.sh
source /usr/local/opt/asdf/etc/bash_completion.d/asdf.bash
