secure_input_notification: false

matches:
  # Simple text replacement
  - trigger: ":nwn"
    replace: "Nick Wolf"

  - trigger: ":nww"
    replace: "https://nickwolf.com.au/"

  - trigger: ":nwg"
    replace: "https://github.com/quintrino"

  - trigger: ":nwt"
    replace: "https://twitter.com/quintrino"

  - trigger: ":nwl"
    replace: "https://www.linkedin.com/in/quintrino/"

  - trigger: ":hp"
    replace: "[High Priority]"

  - trigger: ":mp"
    replace: "[Medium Priority]"

  - trigger: ":lp"
    replace: "[Low Priority]"

  - trigger: ":dl"
    replace: "[Deadline: $|$]"

  - trigger: ":job"
    replace: "Software Engineer"

  - trigger: ":gh"
    replace: "https://github.com/"

  - trigger: ":template"
    replace: |
      ---
      icon: fa-
      permalink: blog/
      categories: Blog
      ---

  - trigger: ":text"
    replace: |
      - trigger: ""
        replace: ""

  - trigger: ":lk"
    replace: "---\nlink: {{clip}}\n---\n$|$"
    vars:
      - name: "clip"
        type: "clipboard"

  - trigger: ":post"
    replace: "e _posts/{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Code

  - trigger: ":bind"
    replace: "require 'pry'; binding.pry"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  - trigger: ":sid"
    replace: |
      Something I did that I liked:

      Something you did that I liked:

      Something for next time:

  - trigger: ":hl"
    replace: "Highlight:: "

  - trigger: ":le"
    replace: "Lesson:: "

  - trigger: ":dc"
    replace: "Decision:: "

  - trigger: ":meet"
    replace: "[Meeting](Meetings/{{date}}-$|$)"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":peop"
    replace: "[[People/$|$]]"
