name: update
root: ~

pre_window: tmux set pane-border-status top

on_project_exit: echo 'update complete'

pre_window: 'clear && ZDOTDIR=~/.config/zsh/ /usr/local/bin/zsh && exit'

windows:
  - update_format:
      panes:
        - tmux_title "VS Code" && vscode_update; tmux_pane
        - tmux_title "Brew Doctor" && doctor_update; tmux_pane
        - tmux_title "Brew" && brew_update; tmux_pane
        - tmux_title "Zinit" && zinit_update; tmux_pane
        - tmux_title "Organize" && organize run; tmux_pane
        - tmux_title "asdf" && asdf_update | rg -v "origin/master|already installed"; tmux_pane
        - tmux_title "Fresh" && fresh_update; tmux_pane
        - tmux_title "Ruby" && ruby_update | rg -v 'Using'; tmux_pane
        - tmux_title "Mac Software" && mac_software_update; tmux_pane
        - tmux_title "Fisher" && fisher_update; tmux_pane
        - sh -c 'sleep 5 && tmuxinator stop update' & tmux choose-session \
