#!/bin/fish

bind \cy 'commandline -f accept-autosuggestion execute'
# Alacritty Command + Enter to auto accept suggestion
bind \ee 'e .; commandline -f repaint'
# Alacritty Command + e Edit directory
bind \ec 'cd (commandline -b); commandline -f repaint'
# Alacritty Control + Option + C to cd into directory
bind \cb backward-kill-line
# Alacritty Command + Backspace to delete full line
