#!/bin/fish

bind \e\[\[CE 'commandline -f accept-autosuggestion execute'
bind \cy 'commandline -f accept-autosuggestion execute'
bind \ce 'e (commandline -b)'
bind \cc 'cd (commandline -b)'
bind \cb backward-kill-line
# Alacritty Command + Backspace to delete full line
