#!/bin/fish

fish_add_path $FRESH_BIN_PATH
set fish_greeting

function __fish_preexec_history --on-event fish_preexec
  if not test -d $XDG_DATA_HOME/fish/history
    mkdir -p $XDG_DATA_HOME/fish/history
  end
  echo "["(date)"]" $fish_pid $USER $PWD";" $argv >> "$XDG_DATA_HOME/fish/history/history-"(date +%Y%m%d)
end

function fish_title
    echo (pwd | awk '{ sub("/Users/nick.wolf", "~"); print $0 }')
end

for file in $XDG_DATA_HOME/environment/*
    source $file
end

function git_check
  git -C $argv[1] rev-parse 2>/dev/null
  if test $status -eq 128
    echo "$argv[1] does not exist or is not a git repository"
    return 128
  end
  set starting_directory (pwd)
  cd $argv[1]
  git fetch --quiet >/dev/null & disown
  git diff --quiet --ignore-submodules HEAD
  if test $status -eq 1
    echo "WARNING: $argv[2] has unsynchronized changes"
  end
  cd $starting_directory
  set -e starting_directory
end

git_check $HOME/.dotfiles 'Dotfiles'
git_check $HOME/Documents/obsidian 'Obsidian'
git_check $HOME/.config/alfred/Alfred.alfredpreferences 'Alfred'

source <%= ("#{`brew --prefix asdf`.chomp}/asdf.fish") || ''%>

starship init fish | source
zoxide init fish --cmd f | source
