#!/bin/bash

# Login to Bitwarden
bw login

# Unlock Bitwarden and get session key
bw_key=$(bw unlock | awk '/$ export BW_SESSION=/{print $NF}')

# Sync Bitwarden
bw sync --session "$bw_key"

# Set data directory
data_dir="${XDG_DATA_HOME:-$HOME/.local/share}"

xdg_env_dir="$data_dir/environment"

# Create environment directory if it doesn't exist
mkdir -p "$xdg_env_dir"

# Get Environment folder ID
env_id=$(bw list folders --search Environment --session "$bw_key" | jq -r '.[0].id')

# Get items in the Environment folder
env_folder=$(bw list items --folderid "$env_id" --session "$bw_key")

# Process each item in the folder
echo "$env_folder" | jq -c '.[]' | while read -r item; do
    filename="$xdg_env_dir/$(echo "$item" | jq -r '.name')"

    # Make file writable if it exists
    [ -f "$filename" ] && chmod +w "$filename"

    # Write content to file
    echo "$item" | jq -r '.notes' > "$filename"

    # Make file read-only
    chmod -w "$filename"
done

echo "Environment variables synced to $xdg_env_dir"
