#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
else
  if [ -f $1 ]; then
    case $1 in
      *.tar.bz2)   tar xvjf ${@}    ;;
      *.tar.gz)    tar xvzf ${@}    ;;
      *.tar.xz)    tar xvJf ${@}    ;;
      *.lzma)      unlzma ${@}      ;;
      *.bz2)       bunzip2 ${@}     ;;
      *.rar)       unrar x -ad ${@} ;;
      *.gz)        gunzip ${@}      ;;
      *.tar)       tar xvf ${@}     ;;
      *.tbz2)      tar xvjf ${@}    ;;
      *.tgz)       tar xvzf ${@}    ;;
      *.zip)       unzip ${@}       ;;
      *.Z)         uncompress ${@}  ;;
      *.7z)        7z x ${@}        ;;
      *.xz)        unxz ${@}        ;;
      *.exe)       cabextract ${@}  ;;
      *)           echo "extract: '$1' - unknown archive method" ;;
    esac
  else
    echo "$1 - file does not exist"
  fi
fi
