#!/bin/sh

. "${ZINIT[HOME_DIR]}/bin/zinit.zsh"

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zpcompinit

zinit ice silent wait'0'
zinit light djui/alias-tips
export ZSH_PLUGINS_ALIAS_TIPS_REVEAL=1
export ZSH_PLUGINS_ALIAS_TIPS_REVEAL_TEXT='\033[0m\033[94mAlias for: \033[1;94m'

zinit ice silent wait'0'
zinit light zdharma/fast-syntax-highlighting

zinit ice silent wait'0'
zinit light rupa/z

zinit ice silent wait'0'
zinit light andrewferrier/fzf-z
export FZFZ_EXTRA_OPTS="--height '25%'"
export FZFZ_PREVIEW_COMMAND='exa {} --tree --git --long --header --color=always'

zinit ice silent wait'0'
zinit light wfxr/forgit
forgit_diff=gid
forgit_restore=forgit_restore

zinit ice silent wait'1' atload'_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions
bindkey '^[[[CE' autosuggest-execute
export ZSH_AUTOSUGGEST_IGNORE_WIDGETS=(fzfz-file-widget)
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=cyan'
