#!/bin/sh

. "${ZINIT[HOME_DIR]}/bin/zinit.zsh"

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zpcompinit

zinit ice lucid wait
zinit light djui/alias-tips
export ZSH_PLUGINS_ALIAS_TIPS_REVEAL=1
export ZSH_PLUGINS_ALIAS_TIPS_REVEAL_TEXT='\033[0m\033[94mAlias for: \033[1;94m'

zinit ice silent wait
zinit light zdharma/fast-syntax-highlighting

zinit ice lucid wait

zinit ice lucid wait
zinit light wfxr/forgit
forgit_diff=gid
forgit_restore=forgit_restore

zinit wait:1 lucid atload"abbr import-aliases --quiet 2> /dev/null &|" for olets/zsh-abbr

zinit ice lucid wait:1 atload:_zsh_autosuggest_start
zinit light zsh-users/zsh-autosuggestions
bindkey '^[[[CE' autosuggest-execute
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=cyan'
