
# Config version for compatibility and deprecations
# See: https://nikitabobko.github.io/AeroSpace/guide#config-version
# Fallback value (if you omit the key): config-version = 1
config-version = 2

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

on-window-detected = [
    # Floating windows - without workspace assigned
    {
        if = '''
        test %{app-bundle-id} = com.apple.calculator \
            || test %{app-bundle-id} = com.apple.clock \
            || test %{app-bundle-id} = com.apple.systempreferences \
            || test %{app-bundle-id} = com.jins.naivechat
            ''',
        run = ['layout floating'],
    },
    # Per workspace location
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    #
    # Workspace 1 (Private)
    {
        if = '''
        test %{app-bundle-id} = com.apple.mail \
            || test %{app-bundle-id} = com.apple.Music \
            || test %{app-bundle-id} = com.apple.MobileSMS \
            || test %{app-bundle-id} = com.apple.TV \
            || test %{app-bundle-id} = com.apple.Photos \
        ''',
        run = ['move-node-to-workspace 1', 'layout floating'],
    },
    # Workspace Vol (Brave Beta)
    {
        if = 'test %{app-bundle-id} = com.brave.Browser.beta',
        run = ['move-node-to-workspace Vol', 'layout tiling', 'fullscreen'],
    },
    # Workspace Sg (Signal Beta)
    {
        if = 'test %{app-bundle-id} = org.whispersystems.signal-desktop-beta',
        run = ['move-node-to-workspace Sg', 'layout tiling', 'fullscreen'],
    },
    # Workspace Bb (Beeper)
    {
        if = 'test %{app-bundle-id} = com.automattic.beeper.desktop',
        run = ['move-node-to-workspace Bb', 'layout tiling', 'fullscreen'],
    },
    # Workspace Tk (Godspeed)
    {
        if = 'test %{app-bundle-id} = com.godspeedapp.Godspeed',
        run = ['move-node-to-workspace Tk', 'layout tiling', 'fullscreen'],
    },
    # Workspace Sk (Slack)
    {
        if = 'test %{app-bundle-id} = com.tinyspeck.slackmacgap',
        run = ['move-node-to-workspace Sk', 'layout tiling', 'fullscreen'],
    },
    # Workspace T (Alacritty)
    {
        if = 'test %{app-bundle-id} = org.alacritty',
        run = ['move-node-to-workspace T', 'layout tiling', 'fullscreen'],
    },
    # Workspace Hd (Firefox)
    {
        if = 'test %{app-bundle-id} = org.mozilla.firefox',
        run = ['move-node-to-workspace Hd', 'layout tiling', 'fullscreen'],
    },
    # Workspace Em (eM Client)
    {
        if = 'test %{app-bundle-id} = com.emclient.mail.client',
        run = ['move-node-to-workspace Em', 'layout tiling', 'fullscreen'],
    },
    # Workspace Ed (Zed)
    {
        if = 'test %{app-bundle-id} = dev.zed.Zed',
        run = ['move-node-to-workspace Ed', 'layout tiling', 'fullscreen'],
    },
    # Workspace Zm (Zoom)
    {
        if = 'test %{window-title} = "Zoom Workspace"',
        run = ['move-node-to-workspace Zm', 'layout tiling', 'fullscreen'],
    },
     {
        if = 'test %{window-title} = "Zoom Meeting"',
        run = ['move-node-to-workspace Zm', 'layout tiling', 'fullscreen'],
    },
    # Workspace B (Zen Browser)
    {
        if = 'test %{app-bundle-id} = app.zen-browser.zen',
        run = ['move-node-to-workspace B', 'layout tiling', 'fullscreen'],
    },
    # Catch-all: anything not matched above goes to workspace 1
    {
        if = 'true',
        run = ['layout floating']
        # run = ['move-node-to-workspace 1', 'layout tiling'],
    },
]

focus-follows-mouse.enabled = false
accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = false
persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    ctrl-h = 'focus --boundaries-action wrap-around-the-workspace left'
    ctrl-j = 'focus --boundaries-action wrap-around-the-workspace down'
    ctrl-k = 'focus --boundaries-action wrap-around-the-workspace up'
    ctrl-l = 'focus --boundaries-action wrap-around-the-workspace right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-ctrl-h = 'move left'
    alt-ctrl-j = 'move down'
    alt-ctrl-k = 'move up'
    alt-ctrl-l = 'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'

    ctrl-alt-left =  ['move-node-to-workspace 1 --focus-follows-window', 'fullscreen off' , 'move left']
    ctrl-alt-right =  ['move-node-to-workspace 1 --focus-follows-window', 'fullscreen off' , 'move right']
    ctrl-alt-up =  ['move-node-to-workspace 1 --focus-follows-window', 'fullscreen off' , 'move up']
    ctrl-alt-down =  ['move-node-to-workspace 1 --focus-follows-window', 'fullscreen off' , 'move down']
    cmd-ctrl-alt-left = 'exec-and-forget $(brew --prefix)/bin/aerospace list-workspaces --monitor focused --empty no | grep -v "1" | cat - <(echo 1) | $(brew --prefix)/bin/aerospace workspace --wrap-around --stdin prev'
    cmd-ctrl-alt-right = 'exec-and-forget $(brew --prefix)/bin/aerospace list-workspaces --monitor focused --empty no | grep -v "1" | cat - <(echo 1) | $(brew --prefix)/bin/aerospace workspace --wrap-around --stdin next'

    # Fullscreen
    ctrl-alt-enter = 'exec-and-forget ~/.dotfiles/shell/utilities/aerospace_toggle'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-tab = 'workspace-back-and-forth'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    alt-shift-tab = ['move-node-to-monitor --wrap-around next', 'focus-monitor --wrap-around next']

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-shift-semicolon = 'mode service'
    alt-shift-f = 'layout floating tiling'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
    1 = 'LEN L27m-28'
    2 = 'LEN L27m-28'
    3 = 'LEN L27m-28'
    4 = 'LEN L27m-28'
    11 = 'LEN L27m-28'
    12 = 'LEN L27m-28'
    13 = 'LEN L27m-28'
    14 = 'LEN L27m-28'
    5 = 'SyncMaster'
    6 = 'SyncMaster'
    7 = 'SyncMaster'
    8 = 'SyncMaster'
    15 = 'SyncMaster'
    16 = 'SyncMaster'
    17 = 'SyncMaster'
    18 = 'SyncMaster'
    Sg = 'SyncMaster'

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

