#!/bin/zsh
# freshshell.com
#
# Examples:
#
#   fresh twe4ked/dotfiles shell/functions/\*
#   fresh jasoncodes/dotfiles shell/aliases/rails.sh
#   fresh jasoncodes/dotfiles config/tmux.conf --file
#
# See http://freshshell.com/readme for documentation.

fresh shell/zsh/zshrc --file=$XDG_CONFIG_HOME/zsh/.zshrc
fresh shell/bash/bashrc --file=$XDG_CONFIG_HOME/bash/profile

fresh-options --filter='erb -T -'
  fresh shell/path
  fresh shell/environment
  fresh shell/zsh/zsh
  fresh shell/zsh/zinit
  fresh shell/aliases
  fresh shell/zsh/functions
  fresh shell/zsh/fzf.zsh
  fresh shell/zsh/local
  fresh shell/zsh/completions
fresh-options

fresh-options --bin
  fresh freshshell/fresh bin/fresh
  fresh freshshell/fresh-open bin/fresh-open
  fresh shell/utilities/calendar_importer
  fresh shell/utilities/extract
  fresh shell/utilities/asdf_cleanse
  fresh shell/utilities/toggle_full_screen
  fresh shell/utilities/apple_select
  fresh shell/utilities/beeminder
fresh-options

fresh-options --file=$XDG_CONFIG_HOME/bash/bash
  fresh shell/path
  fresh shell/environment
fresh-options

# Fish

fresh-options --filter='ABBR_COMPLIANT=1 erb -T -' --file=~/.config/fish/config.fish
  fresh shell/path
  fresh shell/environment
  fresh shell/aliases
  fresh shell/fish/config
  fresh shell/fish/bindings
  fresh shell/fish/functions
fresh-options


# Config
fresh config/espanso --file=~/.config/espanso/
fresh config/mtmr/items.json --file=$HOME/Library/ApplicationSupport/MTMR/items.json
fresh config/organize/config.yaml --file=$XDG_CONFIG_HOME/organize/config.yaml
fresh config/tmux/tmux.conf --file=$XDG_CONFIG_HOME/tmux/tmux.conf
fresh config/tmuxinator/update --file=$XDG_CONFIG_HOME/tmuxinator/update.yml
fresh config/starship/starship --file=$XDG_CONFIG_HOME/starship.toml
fresh config/alacritty/alacritty.yml --file=~/.config/alacritty/alacritty.yml

fresh-options --filter='erb -T -'
  fresh config/beeminder/bmndrrc --file=$XDG_CONFIG_HOME/.bmndrrc
  fresh config/exercism/user.json --file=$XDG_CONFIG_HOME/exercism/user.json
fresh-options


# Git
fresh config/git/cc_menu --bin
fresh config/git/push_alert --bin
fresh config/git/ignore --file=$XDG_CONFIG_HOME/git/ignore
fresh config/git/config --file=$XDG_CONFIG_HOME/git/config --filter=erb

# fresh profile
fresh language/ruby/pryrc --file=$XDG_CONFIG_HOME/pry/pryrc
fresh language/ruby/irbrc --file=$XDG_CONFIG_HOME/ruby/irbrc
fresh language/ruby/gemrc --file=$XDG_CONFIG_HOME/ruby/gemrc
fresh language/nodejs/npmrc --file=$XDG_CONFIG_HOME/npm/npmrc
fresh language/nodejs/default-packages --file=$XDG_CONFIG_HOME/asdf/default-npm-packages
fresh language/ruby/default-gems --file=$XDG_CONFIG_HOME/asdf/default-gems
fresh language/ruby/railsrc --file=$XDG_CONFIG_HOME/rails/railsrc
fresh language/ruby/rspec --file=$XDG_CONFIG_HOME/rspec/options
fresh config/asdf/asdfrc --file=$XDG_CONFIG_HOME/asdf/asdfrc
fresh config/hammerspoon/init.lua --file=$XDG_CONFIG_HOME/hammerspoon/init.lua

fresh_after_build(){
  ln -sf ~/.dotfiles/apps/vlc/vlcrc ~/Library/Preferences/org.videolan.vlc/vlcrc
  ln -sf ~/.dotfiles/apps/vs-code/settings.vsrc ~/Library/Application\ Support/Code/User/settings.json
  ln -sf ~/.dotfiles/apps/vs-code/keys.vsrc ~/Library/Application\ Support/Code/User/keybindings.json
  ln -sf ~/.dotfiles/config/karabiner/karabiner.json $XDG_CONFIG_HOME/karabiner/karabiner.json
  ln -sf ~/Drive/Sync/Mac/Espanso/private.yml $XDG_CONFIG_HOME/espanso/user/private.yml
  ln -sf ~/.dotfiles/shell/fish/plugins $XDG_CONFIG_HOME/fish/fish_plugins
}
