#!/bin/zsh
# freshshell.com
#
# Examples:
#
#   fresh twe4ked/dotfiles shell/functions/\*
#   fresh jasoncodes/dotfiles shell/aliases/rails.sh
#   fresh jasoncodes/dotfiles config/tmux.conf --file
#
# See http://freshshell.com/readme for documentation.


if [ -z "${FRESH_ASDF_STATIC:-}" ]; then
  fresh-options --filter='erb -r $HOME/.dotfiles/config/asdf/latest_version -T -'
      fresh config/asdf/tool-versions --file=$XDG_CONFIG_HOME/asdf/.tool-versions
  fresh-options
else
  fresh config/asdf/tool-versions --file=$XDG_CONFIG_HOME/asdf/.tool-versions
fi

fresh freshshell/fresh bin/fresh --bin
fresh shell/zsh/zshrc --file=~/.zshrc
fresh shell/bash/bashrc --file=$XDG_CONFIG_HOME/bash/profile

fresh-options --filter='erb'
  fresh shell/path
  fresh shell/environment
  fresh shell/zsh/zsh
  fresh shell/zsh/zinit
  fresh shell/zsh/aliases
  fresh shell/zsh/functions
  fresh shell/zsh/fzf.zsh
  fresh shell/zsh/lessrc
  fresh shell/zsh/local
  fresh shell/zsh/completions
fresh-options

fresh shell/utilities/extract --bin
fresh shell/utilities/asdf_cleanse --bin
fresh shell/utilities/toggle_full_screen --bin


fresh-options --file=$XDG_CONFIG_HOME/bash/bash
  fresh shell/path
  fresh shell/environment
fresh-options

fresh config/espanso --file=~/.config/espanso/
fresh config/mtmr/items.json --file=$HOME/Library/ApplicationSupport/MTMR/items.json
fresh config/tmux/tmux.conf --file=$XDG_CONFIG_HOME/tmux/tmux.conf
fresh config/tmuxinator/update --file=$XDG_CONFIG_HOME/tmuxinator/update.yml
fresh config/starship/starship --file=$XDG_CONFIG_HOME/starship.toml

# Git
fresh config/git/cc_menu --bin
fresh config/git/push_alert --bin
fresh config/git/ignore --file=$XDG_CONFIG_HOME/git/ignore
fresh config/git/config --file=$XDG_CONFIG_HOME/git/config --filter=erb

# fresh profile
fresh language/ruby/pryrc --file=$XDG_CONFIG_HOME/pry/pryrc
fresh language/ruby/irbrc --file=$XDG_CONFIG_HOME/ruby/irbrc
fresh language/ruby/gemrc --file=$XDG_CONFIG_HOME/ruby/gemrc
fresh language/nodejs/npmrc --file=$XDG_CONFIG_HOME/npm/npmrc
fresh language/ruby/default-gems --file=$XDG_CONFIG_HOME/asdf/default-gems
fresh language/ruby/railsrc --file=$XDG_CONFIG_HOME/rails/railsrc
fresh language/ruby/rspec --file=$XDG_CONFIG_HOME/rspec/options
fresh config/asdf/asdfrc --file=$XDG_CONFIG_HOME/asdf/asdfrc
fresh config/hammerspoon/init.lua --file=$XDG_CONFIG_HOME/hammerspoon/init.lua

fresh_after_build(){
  ln -sf ~/.dotfiles/apps/vlc/vlcrc ~/Library/Preferences/org.videolan.vlc/vlcrc
  ln -sf ~/.dotfiles/apps/vs-code/settings.vsrc ~/Library/Application\ Support/Code/User/settings.json
  ln -sf ~/.dotfiles/apps/vs-code/keys.vsrc ~/Library/Application\ Support/Code/User/keybindings.json
  ln -sf ~/.dotfiles/config/karabiner/karabiner.json $XDG_CONFIG_HOME/karabiner/karabiner.json
  ln -sf ~/Drive/Sync/Mac/Espanso/private.yml $XDG_CONFIG_HOME/espanso/user/private.yml
}
