matches:
#Self
  - trigger: ":nwn"
    replace: Nick Wolf
  - trigger: ":nww"
    replace: "https://nickwolf.com.au/"
  - trigger: ":nwg"
    replace: "https://github.com/quintrino"
  - trigger: ":nwt"
    replace: "https://twitter.com/quintrino"
  - trigger: ":nwl"
    replace: "https://www.linkedin.com/in/quintrino/"
  - trigger: ":nf"
    replace: "https://nick.wf/"
  - trigger: ":job"
    replace: Software Engineer
#Priority
  - trigger: ":hp"
    replace: "[High Priority]"
  - trigger: ":mp"
    replace: "[Medium Priority]"
  - trigger: ":lp"
    replace: "[Low Priority]"
  - trigger: ":dl"
    replace: "[Deadline: $|$]"
#Blogging
  - trigger: ":template"
    replace: |
      ---
      icon: fa-
      permalink: blog/
      categories: Blog
      ---
  - trigger: ":post"
    replace: "e _posts/{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"
#Programming
  - trigger: ":text"
    replace: "#$|$\"\"\n- trigger: \"\"\n  replace: \"\"\n"
  - trigger: ":bind"
    replace: "require 'pry'; binding.pry"
  - trigger: ":gh"
    replace: "https://github.com/"
  - trigger: ":lk"
    replace: |-
      ---
      link: {{clipboard}}
      ---
      $|$
    vars:
      - name: clipboard
        type: clipboard
  #"Godspeed"
  - trigger: ":go:p"
    replace: "sort:label:Eternal|Vital|high|medium|low"
  - trigger: ":date"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"
#Journalling
  - trigger: ":hl"
    replace: "Highlight:: "
  - trigger: ":le"
    replace: "Lesson:: "
  - trigger: ":ir"
    replace: "InvisibleRule:: "
  - trigger: ":vi"
    replace: "Victory:: "
  - trigger: ":dc"
    replace: "Decision:: "
  - trigger: ":em"
    replace: "Emotion:: "
  - trigger: ":meet"
    replace: "[Meeting](Meetings/{{date}}-$|$)"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ":peop"
    replace: "[[People/$|$]]"
#"Markdown"
  - trigger: ":h1"
    replace: "# "
  - trigger: ":h2"
    replace: "## "
  - trigger: ":h3"
    replace: "### "
  - trigger: ":h4"
    replace: "#### "
  - trigger: ":h5"
    replace: "##### "
  - trigger: ":h6"
    replace: "###### "
  - trigger: "1#"
    replace: "# "
  - trigger: "2#"
    replace: "## "
  - trigger: "3#"
    replace: "### "
  - trigger: "4#"
    replace: "#### "
  - trigger: "5#"
    replace: "##### "
  - trigger: "6#"
    replace: "###### "
  - trigger: ":table"
    replace: |
      | Header 1 | Header 2 | Header 3 |
      | -------- | -------- | -------- |
      | Content 1 | Content 2 | Content 3 |
#Emoji
  - trigger: ":)"
    replace: "🙂"
  - trigger: ":p"
    replace: "😛"
  - trigger: ":P"
    replace: "😛"
  - trigger: ";)"
    replace: "😉"
  - trigger: ":("
    replace: "🙁"
  - trigger: ":D"
    replace: "😃"
  - trigger: ":joy"
    replace: "😂"
  - trigger: ":tableflip:"
    replace: "(╯°□°）╯︵ ┻━┻"
  - trigger: ":fliptable:"
    replace: "(╯°□°）╯︵ ┻━┻"
  - trigger: ":fixtable:"
    replace: "┬─┬ノ( º _ ºノ)"
  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"
  - trigger: ":st1"
    replace: "⭐"
  - trigger: ":st2"
    replace: "⭐⭐"
  - trigger: ":st3"
    replace: "⭐⭐⭐"
  - trigger: ":st4"
    replace: "⭐⭐⭐⭐"
  - trigger: ":st5"
    replace: "⭐⭐⭐⭐⭐"
  - trigger: ":gs"
    replace: "⚡GodSpeed"
